version: '3.8'
services:
  items_api_service:
    image: items_api:latest
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    networks:
      - mysql_network  #  custom network
  db:
    image: mysql:latest
    # referencing the .env file
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root_password  #  strong root password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  #  volume name and host directory path
    networks:
      - mysql_network  #  custom network
volumes:
    mysql-data:
     driver: local

# Define networks
networks:
  mysql_network:
    driver: bridge
